server:
  port: 8080
  # debug | release | test 运行环境
  level: debug
  domain: https://zglndlls.top

datasource:
  host: postgres
  port: 5432
  username: wechatapp1
  password: 20000107
  db_name: wechatapp1
  config: sslmode=disable&TimeZone=Asia/Shanghai
  db_type: PostgreSql

redis:
  host: postgres
  port: 6379
  password: 20000107
  data_base: 1

log:
  level: debug
  filepath: ./logger/systemLog.txt


jwt:
  secret: 8xQ$9pL#2kF!7sR@5zG&1bN*0dH



alioss:
  endpoint: YouOption
  access_key_id: YouOption
  access_key_secret: YouOption
  bucket_name: YouOption

wechat:
  appid: wx3d26ceacc420b29b
  secret: a7d6fbf72c9dc13d085231a5d8287cd8