server:
  port: 8080
  domain: https://zglndlls.top:8443

datasource:
  host: postgres
  port: 5432
  username: wechatapp1
  password: 20000107
  db_name: wechatapp1
  config: sslmode=disable&TimeZone=Asia/Shanghai
  db_type: PostgreSql

redis:
  host: redis
  port: 6379
  password: 20000107
  data_base: 1

log:
  level: debug
  filepath: ./logger/systemLog.txt


jwt:
  secret: 8xQ$9pL#2kF!7sR@5zG&1bN*0dH



alioss:
  endpoint: YouOption
  access_key_id: YouOption
  access_key_secret: YouOption
  bucket_name: YouOption

wechat:
  appid: wx31fa6f8c4ddade95
  secret: 9b14e545f80e4638250e0b5fbe351e5e