server:
  port: 8080
  # debug | release | test 运行环境
  level: debug
  domain: http://192.168.232.128:8080

datasource:
  host: 192.168.232.128
  port: 5432
  username: wechatapp1
  password: 20000107
  db_name: wechatapp1
  config: sslmode=disable&TimeZone=Asia/Shanghai
  db_type: PostgreSql

redis:
  host: 192.168.232.128
  port: 6379
  password: 20000107
  data_base: 1

log:
  level: debug
  filepath: ./logger/systemLog.txt


jwt:
  secret: 8xQ$9pL#2kF!7sR@5zG&1bN*0dH



alioss:
  endpoint: YouOption
  access_key_id: YouOption
  access_key_secret: YouOption
  bucket_name: YouOption

wechat:
  appid: wx845d22cf7a5e4a85
  secret: bdd95e990f24c3098a918f3519ecc7cc